name = "cloudflare-html-rewrite-example"
main = "src/index.ts"
compatibility_date = "2023-12-18"

workers_dev = false

[vars]
ENVIRONMENT = "production"
DEBUG_LOGS = "0"

[env.dev]
workers_dev = true

[env.dev.vars]
ENVIRONMENT = "development"
DEBUG_LOGS = "1"

# SHOP_URL value should use canonical www/non-www form to avoid redirects
SHOP_URL = "https://teamtailorcdn.com/"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
